print("Parabéns" + "!" * 10)
print("Aqui vai um dinossauro!")
print(" "*12+"_"*2)
print(" "*11+"/"+" _)")
print(" "*4+".-"+"^"*3+"-"+"/ /")
print(" "+"_"*2 +"/" + " "*7 +"/")
print("<" + "_"*2 + "." + "|_|-|_|")
print()
print("E aqui vai um bolo! hu" + "m"*8)
print(" ." * 10)
print(" i" * 10)
print("#"*20)
print("=" * 20)
print("#"*20)
print("=" * 20)
print("#"*20)